CATALOGS = {
    "ru": dict(start="старт", previous="Предыдущая неделя", history="История по неделям",
               shown="Показано {visible} из {total}", subtitle="Недельная динамика",
               last="Последняя полная неделя", reps="повторений", best="Лучшее из показанных",
               average="Среднее за показанные недели", per_week="/ нед."),
    "en": dict(start="start", previous="Previous week", history="Weekly history",
               shown="Showing {visible} of {total}", subtitle="Weekly progress",
               last="Last complete week", reps="reps", best="Best shown week",
               average="Average of shown weeks", per_week="/ week"),
    "es": dict(start="inicio", previous="Semana anterior", history="Historial semanal",
               shown="Se muestran {visible} de {total}", subtitle="Progreso semanal",
               last="Última semana completa", reps="repeticiones", best="Mejor semana mostrada",
               average="Promedio de las semanas mostradas", per_week="/ semana"),
    "pt": dict(start="início", previous="Semana anterior", history="Histórico semanal",
               shown="Mostrando {visible} de {total}", subtitle="Progresso semanal",
               last="Última semana completa", reps="repetições", best="Melhor semana exibida",
               average="Média das semanas exibidas", per_week="/ semana"),
    "tr": dict(start="başlangıç", previous="Önceki hafta", history="Haftalık geçmiş",
               shown="{total} haftanın {visible}'si gösteriliyor", subtitle="Haftalık ilerleme",
               last="Son tamamlanan hafta", reps="tekrar", best="Gösterilen en iyi hafta",
               average="Gösterilen haftaların ortalaması", per_week="/ hafta"),
    "uk": dict(start="початок", previous="Попередній тиждень", history="Історія за тижнями",
               shown="Показано {visible} з {total}", subtitle="Тижневий прогрес",
               last="Останній повний тиждень", reps="повторень", best="Найкращий показаний тиждень",
               average="Середнє за показані тижні", per_week="/ тиждень"),
    "id": dict(start="mulai", previous="Minggu sebelumnya", history="Riwayat mingguan",
               shown="Menampilkan {visible} dari {total}", subtitle="Progres mingguan",
               last="Minggu lengkap terakhir", reps="repetisi", best="Minggu terbaik yang ditampilkan",
               average="Rata-rata minggu yang ditampilkan", per_week="/ minggu"),
    "hi": dict(start="शुरुआत", previous="पिछला सप्ताह", history="साप्ताहिक इतिहास",
               shown="{total} में से {visible} दिखाए गए", subtitle="साप्ताहिक प्रगति",
               last="पिछला पूरा सप्ताह", reps="रेप्स", best="दिखाया गया सर्वश्रेष्ठ सप्ताह",
               average="दिखाए गए सप्ताहों का औसत", per_week="/ सप्ताह"),
    "kk": dict(start="бастау", previous="Алдыңғы апта", history="Апталық тарих",
               shown="{total} ішінен {visible} көрсетілді", subtitle="Апталық ілгерілеу",
               last="Соңғы толық апта", reps="қайталау", best="Көрсетілген ең жақсы апта",
               average="Көрсетілген апталардың орташа мәні", per_week="/ апта"),
    "pl": dict(start="start", previous="Poprzedni tydzień", history="Historia tygodniowa",
               shown="Wyświetlono {visible} z {total}", subtitle="Postępy tygodniowe",
               last="Ostatni pełny tydzień", reps="powtórzeń", best="Najlepszy pokazany tydzień",
               average="Średnia z pokazanych tygodni", per_week="/ tydzień"),
    "fr": dict(start="début", previous="Semaine précédente", history="Historique hebdomadaire",
               shown="{visible} sur {total} affichées", subtitle="Progression hebdomadaire",
               last="Dernière semaine complète", reps="répétitions", best="Meilleure semaine affichée",
               average="Moyenne des semaines affichées", per_week="/ semaine"),
}
