"""Localized copy for the optional Telegram Stars support flow."""

_COPY = {
    "ru": {
        "choose": "⭐ Поддержать Repka\n\nПоддержка добровольная и ничего не открывает. Выберите сумму:",
        "other": "✏️ Другая сумма",
        "enter": "Введите целое число Stars от 1 до {maximum}.",
        "invalid": "Введите целое число Stars от 1 до {maximum}.",
        "title": "Поддержка Repka",
        "description": "Добровольная разовая поддержка проекта",
        "thanks": "Спасибо за поддержку — {amount} ⭐!",
        "unavailable": "Этот счёт больше недоступен. Откройте /support и создайте новый.",
        "processing": "Платёж получен. Подтверждаем его — если сообщение не придёт, напишите /paysupport.",
        "contact": "Опишите вопрос или запрос возврата одним сообщением. Мы передадим его в поддержку.",
        "sent": "Спасибо. Запрос передан в поддержку.",
        "terms": "Условия добровольной поддержки\n\nВы можете разово поддержать Repka через Telegram Stars. Поддержка добровольная, не открывает функции, не влияет на данные или работу бота и не создаёт обязательства платить в будущем. По вопросам платежа или запросу возврата используйте /paysupport. Поддержка Telegram не может решать вопросы по платежам этому боту.",
        "commands": {"support": "Поддержать разработку", "paysupport": "Вопросы и возвраты", "terms": "Условия поддержки"},
    },
    "es": {"choose": "⭐ Apoyar a Repka\n\nEl apoyo es voluntario y no desbloquea funciones. Elige una cantidad:", "other": "✏️ Otra cantidad", "enter": "Introduce un número entero de Stars entre 1 y {maximum}.", "invalid": "Introduce un número entero de Stars entre 1 y {maximum}.", "title": "Apoyo a Repka", "description": "Apoyo voluntario único al proyecto", "thanks": "¡Gracias por apoyar con {amount} ⭐!", "unavailable": "Esta factura ya no está disponible. Abre /support y crea una nueva.", "processing": "Pago recibido. Lo estamos confirmando; si no llega el mensaje, usa /paysupport.", "contact": "Describe tu pregunta o solicitud de reembolso en un mensaje. La enviaremos a soporte.", "sent": "Gracias. Tu solicitud se ha enviado a soporte.", "terms": "Términos del apoyo voluntario\n\nPuedes apoyar a Repka una vez con Telegram Stars. Es voluntario, no desbloquea funciones ni cambia tus datos o el funcionamiento del bot. Para preguntas o reembolsos usa /paysupport.", "commands": {"support": "Apoyar el proyecto", "paysupport": "Pagos y reembolsos", "terms": "Términos del apoyo"}},
    "pt": {"choose": "⭐ Apoiar o Repka\n\nO apoio é voluntário e não desbloqueia recursos. Escolha um valor:", "other": "✏️ Outro valor", "enter": "Digite um número inteiro de Stars entre 1 e {maximum}.", "invalid": "Digite um número inteiro de Stars entre 1 e {maximum}.", "title": "Apoio ao Repka", "description": "Apoio voluntário único ao projeto", "thanks": "Obrigado pelo apoio de {amount} ⭐!", "unavailable": "Esta fatura não está mais disponível. Abra /support e crie uma nova.", "processing": "Pagamento recebido. Estamos confirmando; se a mensagem não chegar, use /paysupport.", "contact": "Descreva sua pergunta ou pedido de reembolso em uma mensagem. Nós o enviaremos ao suporte.", "sent": "Obrigado. Seu pedido foi enviado ao suporte.", "terms": "Termos do apoio voluntário\n\nVocê pode apoiar o Repka uma vez com Telegram Stars. É voluntário, não desbloqueia recursos e não altera seus dados ou o bot. Para dúvidas ou reembolsos use /paysupport.", "commands": {"support": "Apoiar o projeto", "paysupport": "Pagamentos e reembolsos", "terms": "Termos do apoio"}},
    "tr": {"choose": "⭐ Repka'yı destekle\n\nDestek isteğe bağlıdır ve özellik açmaz. Bir miktar seçin:", "other": "✏️ Başka miktar", "enter": "1 ile {maximum} arasında tam Stars sayısı girin.", "invalid": "1 ile {maximum} arasında tam Stars sayısı girin.", "title": "Repka desteği", "description": "Projeye tek seferlik gönüllü destek", "thanks": "{amount} ⭐ desteğiniz için teşekkürler!", "unavailable": "Bu fatura artık kullanılamaz. /support açıp yenisini oluşturun.", "processing": "Ödeme alındı. Onaylıyoruz; mesaj gelmezse /paysupport kullanın.", "contact": "Sorunuzu veya iade isteğinizi tek mesajda yazın. Desteğe ileteceğiz.", "sent": "Teşekkürler. Talebiniz desteğe gönderildi.", "terms": "Gönüllü destek koşulları\n\nRepka'yı Telegram Stars ile bir kez destekleyebilirsiniz. Bu isteğe bağlıdır, özellik açmaz ve verilerinizi veya botun işleyişini değiştirmez. Sorular veya iadeler için /paysupport kullanın.", "commands": {"support": "Projeyi destekle", "paysupport": "Ödemeler ve iadeler", "terms": "Destek koşulları"}},
    "uk": {"choose": "⭐ Підтримати Repka\n\nПідтримка добровільна й не відкриває функцій. Виберіть суму:", "other": "✏️ Інша сума", "enter": "Введіть ціле число Stars від 1 до {maximum}.", "invalid": "Введіть ціле число Stars від 1 до {maximum}.", "title": "Підтримка Repka", "description": "Добровільна одноразова підтримка проєкту", "thanks": "Дякуємо за підтримку — {amount} ⭐!", "unavailable": "Цей рахунок більше недоступний. Відкрийте /support і створіть новий.", "processing": "Платіж отримано. Підтверджуємо його; якщо повідомлення не надійде, напишіть /paysupport.", "contact": "Опишіть запитання або запит на повернення одним повідомленням. Ми передамо його в підтримку.", "sent": "Дякуємо. Запит передано в підтримку.", "terms": "Умови добровільної підтримки\n\nВи можете разово підтримати Repka через Telegram Stars. Це добровільно, не відкриває функцій і не впливає на дані чи роботу бота. Для питань і повернень використовуйте /paysupport.", "commands": {"support": "Підтримати проєкт", "paysupport": "Платежі та повернення", "terms": "Умови підтримки"}},
    "id": {"choose": "⭐ Dukung Repka\n\nDukungan bersifat sukarela dan tidak membuka fitur. Pilih jumlah:", "other": "✏️ Jumlah lain", "enter": "Masukkan jumlah Stars bulat dari 1 hingga {maximum}.", "invalid": "Masukkan jumlah Stars bulat dari 1 hingga {maximum}.", "title": "Dukungan Repka", "description": "Dukungan sukarela satu kali untuk proyek", "thanks": "Terima kasih atas dukungan {amount} ⭐!", "unavailable": "Faktur ini tidak lagi tersedia. Buka /support dan buat yang baru.", "processing": "Pembayaran diterima. Kami sedang mengonfirmasinya; jika pesan tidak tiba, gunakan /paysupport.", "contact": "Jelaskan pertanyaan atau permintaan pengembalian dana dalam satu pesan. Kami akan meneruskannya ke dukungan.", "sent": "Terima kasih. Permintaan Anda telah dikirim ke dukungan.", "terms": "Ketentuan dukungan sukarela\n\nAnda dapat mendukung Repka sekali dengan Telegram Stars. Dukungan sukarela, tidak membuka fitur dan tidak mengubah data atau cara kerja bot. Untuk pertanyaan atau pengembalian dana gunakan /paysupport.", "commands": {"support": "Dukung proyek", "paysupport": "Pembayaran dan refund", "terms": "Ketentuan dukungan"}},
    "hi": {"choose": "⭐ Repka को सहयोग दें\n\nसहयोग स्वैच्छिक है और कोई सुविधा नहीं खोलता। राशि चुनें:", "other": "✏️ दूसरी राशि", "enter": "1 से {maximum} तक Stars की पूर्ण संख्या दर्ज करें।", "invalid": "1 से {maximum} तक Stars की पूर्ण संख्या दर्ज करें।", "title": "Repka सहयोग", "description": "प्रोजेक्ट के लिए एकमुश्त स्वैच्छिक सहयोग", "thanks": "{amount} ⭐ के सहयोग के लिए धन्यवाद!", "unavailable": "यह इनवॉइस अब उपलब्ध नहीं है। /support खोलकर नया बनाएं।", "processing": "भुगतान मिल गया है। पुष्टि हो रही है; संदेश न आए तो /paysupport उपयोग करें।", "contact": "अपना प्रश्न या रिफंड अनुरोध एक संदेश में लिखें। हम इसे सहायता टीम को भेजेंगे।", "sent": "धन्यवाद। आपका अनुरोध सहायता टीम को भेज दिया गया है।", "terms": "स्वैच्छिक सहयोग की शर्तें\n\nआप Telegram Stars से Repka को एक बार सहयोग दे सकते हैं। यह स्वैच्छिक है, कोई सुविधा नहीं खोलता और आपके डेटा या बॉट के काम को नहीं बदलता। प्रश्न या रिफंड के लिए /paysupport उपयोग करें।", "commands": {"support": "प्रोजेक्ट को सहयोग दें", "paysupport": "भुगतान और रिफंड", "terms": "सहयोग की शर्तें"}},
    "kk": {"choose": "⭐ Repka-ны қолдау\n\nҚолдау ерікті және ешбір функцияны ашпайды. Соманы таңдаңыз:", "other": "✏️ Басқа сома", "enter": "1 мен {maximum} арасындағы бүтін Stars санын енгізіңіз.", "invalid": "1 мен {maximum} арасындағы бүтін Stars санын енгізіңіз.", "title": "Repka қолдауы", "description": "Жобаға бір реттік ерікті қолдау", "thanks": "{amount} ⭐ қолдауыңызға рақмет!", "unavailable": "Бұл шот енді қолжетімді емес. /support ашып, жаңасын жасаңыз.", "processing": "Төлем алынды. Растап жатырмыз; хабарлама келмесе, /paysupport пайдаланыңыз.", "contact": "Сұрағыңызды немесе қайтару өтінішін бір хабарламада жазыңыз. Қолдау қызметіне жібереміз.", "sent": "Рақмет. Өтінішіңіз қолдау қызметіне жіберілді.", "terms": "Ерікті қолдау шарттары\n\nRepka-ны Telegram Stars арқылы бір рет қолдай аласыз. Бұл ерікті, функцияларды ашпайды және деректеріңізге не бот жұмысына әсер етпейді. Сұрақтар немесе қайтарымдар үшін /paysupport пайдаланыңыз.", "commands": {"support": "Жобаны қолдау", "paysupport": "Төлемдер мен қайтарымдар", "terms": "Қолдау шарттары"}},
    "pl": {"choose": "⭐ Wesprzyj Repka\n\nWsparcie jest dobrowolne i nie odblokowuje funkcji. Wybierz kwotę:", "other": "✏️ Inna kwota", "enter": "Wpisz całkowitą liczbę Stars od 1 do {maximum}.", "invalid": "Wpisz całkowitą liczbę Stars od 1 do {maximum}.", "title": "Wsparcie Repka", "description": "Jednorazowe dobrowolne wsparcie projektu", "thanks": "Dziękujemy za wsparcie: {amount} ⭐!", "unavailable": "Ta faktura nie jest już dostępna. Otwórz /support i utwórz nową.", "processing": "Płatność otrzymana. Potwierdzamy ją; jeśli wiadomość nie nadejdzie, użyj /paysupport.", "contact": "Opisz pytanie lub prośbę o zwrot w jednej wiadomości. Przekażemy ją do wsparcia.", "sent": "Dziękujemy. Twoje zgłoszenie przekazano do wsparcia.", "terms": "Warunki dobrowolnego wsparcia\n\nMożesz jednorazowo wesprzeć Repka przez Telegram Stars. Wsparcie jest dobrowolne, nie odblokowuje funkcji i nie zmienia danych ani działania bota. W sprawie pytań lub zwrotów użyj /paysupport.", "commands": {"support": "Wesprzyj projekt", "paysupport": "Płatności i zwroty", "terms": "Warunki wsparcia"}},
    "fr": {"choose": "⭐ Soutenir Repka\n\nLe soutien est facultatif et ne débloque aucune fonction. Choisissez un montant :", "other": "✏️ Autre montant", "enter": "Saisissez un nombre entier de Stars entre 1 et {maximum}.", "invalid": "Saisissez un nombre entier de Stars entre 1 et {maximum}.", "title": "Soutien à Repka", "description": "Soutien unique et facultatif au projet", "thanks": "Merci pour votre soutien de {amount} ⭐ !", "unavailable": "Cette facture n’est plus disponible. Ouvrez /support et créez-en une nouvelle.", "processing": "Paiement reçu. Nous le confirmons ; si le message n’arrive pas, utilisez /paysupport.", "contact": "Décrivez votre question ou demande de remboursement en un message. Nous la transmettrons au support.", "sent": "Merci. Votre demande a été transmise au support.", "terms": "Conditions du soutien facultatif\n\nVous pouvez soutenir Repka une fois avec Telegram Stars. Le soutien est facultatif, ne débloque aucune fonction et ne modifie pas vos données ni le bot. Pour les questions ou remboursements, utilisez /paysupport.", "commands": {"support": "Soutenir le projet", "paysupport": "Paiements et remboursements", "terms": "Conditions du soutien"}},
}

_TERMS_CONFIRMATION = {
    "ru": "⭐ Поддержать разработку\n\nRepka бесплатна. Вы можете разово отправить Telegram Stars как добровольную поддержку развития проекта.\n\nПоддержка не открывает функции, не даёт преимуществ, не влияет на данные или работу бота и не создаёт обязательства платить в будущем.\n\nПо вопросам платежа или запросу возврата используйте /paysupport. Поддержка Telegram не может решать вопросы по платежам этому боту.\n\nНажмите кнопку ниже, чтобы подтвердить, что ознакомились с условиями.",
    "es": "⭐ Apoyar al desarrollador\n\nRepka es gratis. Puedes enviar Telegram Stars una vez como apoyo voluntario al desarrollo.\n\nEl apoyo no desbloquea funciones, no da ventajas ni cambia tus datos o el bot, y no crea pagos futuros obligatorios.\n\nPara preguntas de pago o reembolsos usa /paysupport. El soporte de Telegram no puede resolver pagos a este bot.\n\nPulsa el botón para confirmar que has leído los términos.",
    "pt": "⭐ Apoiar o desenvolvedor\n\nO Repka é gratuito. Você pode enviar Telegram Stars uma vez como apoio voluntário ao desenvolvimento.\n\nO apoio não desbloqueia recursos, não dá vantagens, não altera seus dados ou o bot e não cria pagamentos futuros obrigatórios.\n\nPara dúvidas de pagamento ou reembolso use /paysupport. O suporte do Telegram não resolve pagamentos para este bot.\n\nToque no botão para confirmar que leu os termos.",
    "tr": "⭐ Geliştiriciyi destekle\n\nRepka ücretsizdir. Gelişimi için bir kez gönüllü Telegram Stars gönderebilirsiniz.\n\nDestek özellik açmaz, avantaj sağlamaz, verilerinizi veya botu değiştirmez ve gelecekte ödeme yükümlülüğü oluşturmaz.\n\nÖdeme soruları veya iade için /paysupport kullanın. Telegram desteği bu bota yapılan ödemeleri çözemez.\n\nKoşulları okuduğunuzu onaylamak için düğmeye dokunun.",
    "uk": "⭐ Підтримати розробника\n\nRepka безкоштовна. Ви можете разово надіслати Telegram Stars як добровільну підтримку розвитку.\n\nПідтримка не відкриває функцій, не дає переваг, не впливає на дані чи роботу бота й не створює майбутніх платіжних зобов’язань.\n\nДля питань щодо платежу або повернення використовуйте /paysupport. Підтримка Telegram не вирішує платежі цьому боту.\n\nНатисніть кнопку, щоб підтвердити ознайомлення з умовами.",
    "id": "⭐ Dukung pengembang\n\nRepka gratis. Anda dapat mengirim Telegram Stars sekali sebagai dukungan sukarela untuk pengembangan.\n\nDukungan tidak membuka fitur, tidak memberi keuntungan, tidak mengubah data atau bot, dan tidak menciptakan kewajiban pembayaran di masa depan.\n\nUntuk pertanyaan pembayaran atau refund gunakan /paysupport. Dukungan Telegram tidak dapat menyelesaikan pembayaran ke bot ini.\n\nKetuk tombol untuk mengonfirmasi bahwa Anda telah membaca ketentuan.",
    "hi": "⭐ डेवलपर का सहयोग करें\n\nRepka निःशुल्क है। आप विकास के लिए स्वैच्छिक सहयोग के रूप में एक बार Telegram Stars भेज सकते हैं।\n\nसहयोग कोई सुविधा नहीं खोलता, लाभ नहीं देता, आपके डेटा या बॉट को नहीं बदलता और भविष्य के भुगतान का दायित्व नहीं बनाता।\n\nभुगतान या रिफंड के लिए /paysupport उपयोग करें। Telegram सहायता इस बॉट के भुगतान हल नहीं कर सकती।\n\nशर्तें पढ़ने की पुष्टि करने के लिए बटन दबाएँ।",
    "kk": "⭐ Әзірлеушіні қолдау\n\nRepka тегін. Дамуына ерікті қолдау ретінде Telegram Stars-ты бір рет жібере аласыз.\n\nҚолдау функцияларды ашпайды, артықшылық бермейді, деректеріңізге не ботқа әсер етпейді және болашақ төлем міндеттемесін тудырмайды.\n\nТөлем не қайтарым мәселелері үшін /paysupport пайдаланыңыз. Telegram қолдауы бұл бот төлемдерін шеше алмайды.\n\nШарттарды оқығаныңызды растау үшін батырманы басыңыз.",
    "pl": "⭐ Wesprzyj dewelopera\n\nRepka jest darmowa. Możesz raz wysłać Telegram Stars jako dobrowolne wsparcie rozwoju.\n\nWsparcie nie odblokowuje funkcji, nie daje korzyści, nie zmienia danych ani bota i nie tworzy obowiązku przyszłych płatności.\n\nW sprawie płatności lub zwrotu użyj /paysupport. Pomoc Telegrama nie rozwiązuje płatności dla tego bota.\n\nNaciśnij przycisk, aby potwierdzić przeczytanie warunków.",
    "fr": "⭐ Soutenir le développeur\n\nRepka est gratuit. Vous pouvez envoyer une fois des Telegram Stars comme soutien volontaire au développement.\n\nLe soutien ne débloque aucune fonction, ne donne aucun avantage, ne modifie pas vos données ni le bot et ne crée aucune obligation de paiement futur.\n\nPour une question de paiement ou un remboursement, utilisez /paysupport. L’assistance Telegram ne peut pas résoudre les paiements vers ce bot.\n\nAppuyez sur le bouton pour confirmer que vous avez lu les conditions.",
}

_CONTINUE_BUTTONS = {
    "ru": "✓ Ознакомился с условиями", "es": "✓ He leído los términos",
    "pt": "✓ Li os termos", "tr": "✓ Koşulları okudum",
    "uk": "✓ Ознайомився з умовами", "id": "✓ Saya sudah membaca ketentuan",
    "hi": "✓ मैंने शर्तें पढ़ ली हैं", "kk": "✓ Шарттармен таныстым",
    "pl": "✓ Zapoznałem się z warunkami", "fr": "✓ J’ai lu les conditions",
}


def apply_support_translations(namespace: dict[str, object], language: str) -> None:
    copy = _COPY[language]
    namespace.update(
        SUPPORT_CHOOSE_AMOUNT=copy["choose"],
        BUTTON_OTHER_AMOUNT=copy["other"],
        SUPPORT_INVOICE_TITLE=copy["title"],
        SUPPORT_INVOICE_DESCRIPTION=copy["description"],
        SUPPORT_PAYMENT_UNAVAILABLE=copy["unavailable"],
        SUPPORT_PAYMENT_PROCESSING=copy["processing"],
        SUPPORT_PAYMENT_CONTACT=copy["contact"],
        SUPPORT_REQUEST_SENT=copy["sent"],
        SUPPORT_TERMS=copy["terms"],
        SUPPORT_TERMS_CONFIRMATION=_TERMS_CONFIRMATION[language],
        BUTTON_SUPPORT_CONTINUE=_CONTINUE_BUTTONS[language],
        support_amount_button=lambda amount: f"{amount} ⭐",
        support_enter_amount=lambda maximum: copy["enter"].format(maximum=maximum),
        support_invalid_amount=lambda maximum: copy["invalid"].format(maximum=maximum),
        support_thank_you=lambda amount: copy["thanks"].format(amount=amount),
    )
    namespace["BOT_COMMANDS"] = {
        **namespace["BOT_COMMANDS"],
        "support": copy["commands"]["support"],
    }
