"""Spanish Telegram UI copy."""
from .en import *
LANGUAGE_CODE = "es"
LANGUAGE_NAME = "Español"
LANGUAGE_BUTTON = "🇪🇸 Español"
EXERCISES_TITLE = "🏋️ Repka\n\nElige un ejercicio"
NO_EXERCISES = "🏋️ Repka\n\nAún no hay ejercicios"
BUTTON_SETTINGS = "⚙️ Ajustes"
BUTTON_ADD_EXERCISE = "➕ Añadir ejercicio"
BUTTON_ADD_FIRST_EXERCISE = "➕ Añade tu primer ejercicio"
BUTTON_ADD_RESULT = "➕ Añadir resultado"
BUTTON_STATISTICS = "📊 Estadísticas"
BUTTON_HISTORY = "📜 Historial"
BUTTON_BACK = BUTTON_BACK_ARROW = "← Atrás"
BUTTON_CHANGE_LANGUAGE = "🌐 Idioma"
BUTTON_CHANGE_TIMEZONE = "🌍 Zona horaria"
CHOOSE_LANGUAGE = "🌐 Elige un idioma"
LANGUAGE_CHANGED = "Idioma cambiado"
TODAY, YESTERDAY, DAY_BEFORE_YESTERDAY = "Hoy", "Ayer", "Anteayer"
ENTER_RESULT = "Introduce un resultado."
INVALID_RESULT_FORMAT = "Formato no reconocido. Ejemplos: 10, 4x10 o 10 9 8."
INVALID_DATE = "Fecha no reconocida. Usa 25.08, 25.08.2026 o 2026-08-25."
BACKEND_UNAVAILABLE = "El servicio no está disponible temporalmente. Inténtalo más tarde."
BOT_NAME = "Repka · Registro de entrenamiento"
BOT_SHORT_DESCRIPTION = "Registra ejercicios, sigue tu progreso y recibe informes semanales."
BOT_DESCRIPTION = "🥬 Repka es un registro de ejercicios en Telegram.\n\nRegistra series y repeticiones en una línea, consulta tu progreso y recibe informes semanales."
BOT_COMMANDS = {"menu": "Menú", "settings": "Ajustes", "help": "Ayuda"}
WELCOME = "🥬 ¡Hola! Soy Repka.\n\nGuardo tus entrenamientos y convierto números sencillos en una historia clara de tu progreso.\n\nAñade un ejercicio y envíame un resultado como 16, 4×10 o 12, 10, 8."
HELP = "ℹ️ Ayuda\n\nElige un ejercicio para añadir un resultado, ver estadísticas o abrir el historial.\n\n/menu — ejercicios\n/settings — ajustes"
from ._translations import _apply_button_translations
_apply_button_translations(globals(), LANGUAGE_CODE)
