"""Hindi Telegram UI copy."""
from .en import *
LANGUAGE_CODE = "hi"
LANGUAGE_NAME = "Hindi"
LANGUAGE_BUTTON = "🇮🇳 Hindi"
EXERCISES_TITLE = "🏋️ Repka\n\nएक व्यायाम चुनें"
NO_EXERCISES = "🏋️ Repka\n\nअभी कोई व्यायाम नहीं है"
BUTTON_SETTINGS = "⚙️ सेटिंग्स"
BUTTON_ADD_EXERCISE = "➕ व्यायाम जोड़ें"
BUTTON_ADD_FIRST_EXERCISE = "➕ अपना पहला व्यायाम जोड़ें"
BUTTON_ADD_RESULT = "➕ परिणाम जोड़ें"
BUTTON_STATISTICS = "📊 आँकड़े"
BUTTON_HISTORY = "📜 इतिहास"
BUTTON_BACK = BUTTON_BACK_ARROW = "← वापस"
BUTTON_CHANGE_LANGUAGE = "🌐 भाषा"
BUTTON_CHANGE_TIMEZONE = "🌍 समय क्षेत्र"
CHOOSE_LANGUAGE = "🌐 भाषा चुनें"
LANGUAGE_CHANGED = "भाषा बदल दी गई"
TODAY, YESTERDAY, DAY_BEFORE_YESTERDAY = "आज", "कल", "परसों"
ENTER_RESULT = "एक परिणाम दर्ज करें।"
INVALID_RESULT_FORMAT = "प्रारूप पहचाना नहीं गया। उदाहरण: 10, 4x10, या 10 9 8।"
INVALID_DATE = "तारीख पहचानी नहीं गई। 25.08, 25.08.2026 या 2026-08-25 का उपयोग करें।"
BACKEND_UNAVAILABLE = "सेवा अस्थायी रूप से उपलब्ध नहीं है। बाद में फिर कोशिश करें।"
BOT_NAME = "Repka · वर्कआउट ट्रैकर"
BOT_SHORT_DESCRIPTION = "व्यायाम दर्ज करें, अपनी प्रगति देखें और साप्ताहिक रिपोर्ट पाएं।"
BOT_DESCRIPTION = "🥬 Repka, Telegram में व्यायाम ट्रैकर है।\n\nसेट और रेप्स एक पंक्ति में दर्ज करें, प्रगति देखें और साप्ताहिक रिपोर्ट पाएं।"
BOT_COMMANDS = {"menu": "मेनू", "settings": "सेटिंग्स", "help": "मदद"}
WELCOME = "🥬 नमस्ते! मैं Repka हूँ।\n\nमैं आपके वर्कआउट सहेजता हूँ और साधारण संख्याओं को आपकी प्रगति की साफ़ कहानी में बदलता हूँ।\n\nएक व्यायाम जोड़ें और 16, 4×10 या 12, 10, 8 जैसा परिणाम भेजें।"
HELP = "ℹ️ मदद\n\nपरिणाम जोड़ने, आँकड़े देखने या इतिहास खोलने के लिए एक व्यायाम चुनें।\n\n/menu — व्यायाम\n/settings — सेटिंग्स"
from ._translations import _apply_button_translations
_apply_button_translations(globals(), LANGUAGE_CODE)
