"""Indonesian Telegram UI copy."""
from .en import *
LANGUAGE_CODE = "id"
LANGUAGE_NAME = "Bahasa Indonesia"
LANGUAGE_BUTTON = "🇮🇩 Bahasa Indonesia"
EXERCISES_TITLE = "🏋️ Repka\n\nPilih latihan"
NO_EXERCISES = "🏋️ Repka\n\nBelum ada latihan"
BUTTON_SETTINGS = "⚙️ Pengaturan"
BUTTON_ADD_EXERCISE = "➕ Tambah latihan"
BUTTON_ADD_FIRST_EXERCISE = "➕ Tambahkan latihan pertama Anda"
BUTTON_ADD_RESULT = "➕ Tambah hasil"
BUTTON_STATISTICS = "📊 Statistik"
BUTTON_HISTORY = "📜 Riwayat"
BUTTON_BACK = BUTTON_BACK_ARROW = "← Kembali"
BUTTON_CHANGE_LANGUAGE = "🌐 Bahasa"
BUTTON_CHANGE_TIMEZONE = "🌍 Zona waktu"
CHOOSE_LANGUAGE = "🌐 Pilih bahasa"
LANGUAGE_CHANGED = "Bahasa diubah"
TODAY, YESTERDAY, DAY_BEFORE_YESTERDAY = "Hari ini", "Kemarin", "Kemarin lusa"
ENTER_RESULT = "Masukkan hasil."
INVALID_RESULT_FORMAT = "Format tidak dikenali. Contoh: 10, 4x10, atau 10 9 8."
INVALID_DATE = "Tanggal tidak dikenali. Gunakan 25.08, 25.08.2026, atau 2026-08-25."
BACKEND_UNAVAILABLE = "Layanan sementara tidak tersedia. Coba lagi nanti."
BOT_NAME = "Repka · Pelacak Latihan"
BOT_SHORT_DESCRIPTION = "Catat latihan, lihat progres Anda, dan dapatkan laporan mingguan."
BOT_DESCRIPTION = "🥬 Repka adalah pelacak latihan di Telegram.\n\nCatat set dan repetisi dalam satu baris, lihat progres Anda, dan dapatkan laporan mingguan."
BOT_COMMANDS = {"menu": "Menu", "settings": "Pengaturan", "help": "Bantuan"}
WELCOME = "🥬 Hai! Saya Repka.\n\nSaya menyimpan latihan Anda dan mengubah angka sederhana menjadi cerita progres yang jelas.\n\nTambahkan latihan dan kirim hasil seperti 16, 4×10, atau 12, 10, 8."
HELP = "ℹ️ Bantuan\n\nPilih latihan untuk menambahkan hasil, melihat statistik, atau membuka riwayat.\n\n/menu — latihan\n/settings — pengaturan"
from ._translations import _apply_button_translations
_apply_button_translations(globals(), LANGUAGE_CODE)
