"""Polish Telegram UI copy."""
from .en import *

LANGUAGE_CODE = "pl"
LANGUAGE_NAME = "Polski"
LANGUAGE_BUTTON = "🇵🇱 Polski"
BOT_NAME = "Repka · Monitor treningów"
BOT_COMMANDS = {"menu": "Menu", "settings": "Ustawienia", "help": "Pomoc"}
BOT_SHORT_DESCRIPTION = "Zapisuj ćwiczenia, śledź postępy i otrzymuj tygodniowe raporty."
BOT_DESCRIPTION = "🥬 Repka to monitor ćwiczeń w Telegramie.\n\nZapisuj serie i powtórzenia w jednym wierszu, śledź postępy i otrzymuj tygodniowe raporty."
EXERCISES_TITLE = "🏋️ Repka\n\nWybierz ćwiczenie"
NO_EXERCISES = "🏋️ Repka\n\nNie ma jeszcze ćwiczeń"
WELCOME = "🥬 Cześć! Jestem Repka.\n\nZapamiętuję Twoje treningi i zamieniam proste liczby w jasny obraz postępów.\n\nDodaj ćwiczenie i wyślij wynik: 16, 4×10 albo 12, 10, 8."
HELP = "ℹ️ Pomoc\n\nWybierz ćwiczenie, aby dodać wynik, zobaczyć statystyki lub otworzyć historię.\n\n/menu — ćwiczenia\n/settings — ustawienia"
BUTTON_SETTINGS = "⚙️ Ustawienia"
BUTTON_ADD_EXERCISE = "➕ Dodaj ćwiczenie"
BUTTON_ADD_FIRST_EXERCISE = "➕ Dodaj pierwsze ćwiczenie"
BUTTON_ADD_RESULT = "➕ Dodaj wynik"
BUTTON_STATISTICS = "📊 Statystyki"
BUTTON_HISTORY = "📜 Historia"
BUTTON_BACK = BUTTON_BACK_ARROW = "← Wstecz"
BUTTON_CHANGE_LANGUAGE = "🌐 Język"
BUTTON_CHANGE_TIMEZONE = "🌍 Strefa czasowa"
CHOOSE_LANGUAGE = "🌐 Wybierz język"
LANGUAGE_CHANGED = "Język zmieniony"
TODAY, YESTERDAY, DAY_BEFORE_YESTERDAY = "Dziś", "Wczoraj", "Przedwczoraj"
ENTER_RESULT = "Wpisz wynik."
INVALID_RESULT_FORMAT = "Nierozpoznany format. Przykłady: 10, 4x10 albo 10 9 8."
INVALID_DATE = "Nierozpoznana data. Użyj 25.08, 25.08.2026 albo 2026-08-25."
BACKEND_UNAVAILABLE = "Usługa jest chwilowo niedostępna. Spróbuj ponownie później."

from ._translations import _apply_button_translations
_apply_button_translations(globals(), LANGUAGE_CODE)

# Dynamic screens and notifications.  These used to be inherited from en.py.
EXERCISE_NOT_FOUND = "Nie znaleziono ćwiczenia."
REQUEST_EXERCISE_NAME = "Wpisz nazwę ćwiczenia"
EMPTY_EXERCISE_NAME = "Nazwa nie może być pusta. Spróbuj ponownie:"
SCREEN_EXPIRED = "Ten ekran wygasł."
INPUT_FINISHED = "Wprowadzanie zostało już zakończone."
EDIT_FINISHED = "Edycja została już zakończona."
INPUT_CANCELLED = "Anulowano"
ENTRY_NOT_FOUND = "Nie znaleziono wpisu."
DAY_OR_EXERCISE_NOT_FOUND = "Nie znaleziono dnia lub ćwiczenia."
RESTORE_INPUT_FAILED = "Nie udało się przywrócić wprowadzania. Otwórz ćwiczenie ponownie."
RESTORE_ENTRY_FAILED = "Nie udało się przywrócić wpisu."
CHOOSE_DATE = "Wybierz datę:"
CHOOSE_NEW_DATE = "Wybierz nową datę:"
ENTER_DATE = "Wpisz datę:\n\n25.08\n25.08.2026\n2026-08-25"
ENTER_DATE_REQUIRED = "Wpisz datę."
FUTURE_DATE = "Nie można wybrać przyszłej daty."
MIN_REPETITIONS = "Minimum to 1."
MAX_REPETITIONS = "Maksimum to 10 000."
CHANGES_SAVED = "Zmiany zapisane"
ENTRY_DELETED = "Wpis usunięty"
DATE_CHANGED = "Data zmieniona"
RESULT_ADDED = "Dodano"
HISTORY_CLEARED = "Historia wyczyszczona"
ACCESS_FORBIDDEN = "Dostęp do bota jest ograniczony."
RESOURCE_NOT_FOUND = "Nie znaleziono danych. Wyślij /start i spróbuj ponownie."
RESOURCE_CONFLICT = "Ćwiczenie nie jest już dostępne."
DUPLICATE_EXERCISE_NAME = "Ćwiczenie o tej nazwie już istnieje."
REQUEST_FAILED = "Nie udało się wykonać żądania. Spróbuj ponownie później."
POSITIVE_RESULT_REQUIRED = "Liczba serii i powtórzeń musi być dodatnia."
NUMBER_TOO_LARGE = "Liczba jest zbyt duża."
SET_NOT_FOUND = "Nie znaleziono serii."
LAST_SET_REQUIRED = "Musi pozostać co najmniej jedna seria."
EXERCISE_MANAGEMENT = "🛠 Zarządzaj ćwiczeniami"
CLEAR_HISTORY_CHOOSE_EXERCISE = "🧹 Wyczyść historię\n\nWybierz ćwiczenie"
DELETE_EXERCISE_CHOOSE_EXERCISE = "🗑 Usuń ćwiczenie\n\nWybierz ćwiczenie"

def exercise_name_too_long(max_length: int) -> str: return f"Nazwa jest za długa. Maksimum: {max_length} znaków."
def sets_count_out_of_range(max_sets: int) -> str: return f"Liczba serii musi mieścić się między 1 a {max_sets}."
def repetitions_out_of_range(max_repetitions: int) -> str: return f"Liczba powtórzeń w serii musi mieścić się między 1 a {max_repetitions:,}."
def too_many_sets(max_sets: int) -> str: return f"Nie można dodać więcej niż {max_sets} serii."
def exercise_empty(name: str) -> str: return f"🏋️ {name}\n\n↩️ Ostatnio: —\n\n🔥 Dziś — 0\n📅 7 dni — 0\n🗓 30 dni — 0\n🏆 Razem — 0"
def exercise_summary(*, name: str, last_reps: str, last_date: str, today_reps: str, last_7_days_reps: str, last_30_days_reps: str, total_reps: str) -> str: return f"🏋️ {name}\n\n↩️ Ostatnio: {last_reps} · {last_date.lower()}\n\n🔥 Dziś — {today_reps}\n📅 7 dni — {last_7_days_reps}\n🗓 30 dni — {last_30_days_reps}\n🏆 Razem — {total_reps}"
def statistics(**v: str | None) -> str:
    value=f"📊 {v['name']}\n\nDziś: {v['today_reps']}\n7 dni: {v['last_7_days_reps']}\n30 dni: {v['last_30_days_reps']}\nŁącznie: {v['total_reps']}\n\nDni treningowe: {v['active_days']}\nWpisy: {v['entries']}"
    return value if v['best_day'] is None else value+f"\n\nNajlepszy dzień:\n{v['best_day']} — {v['best_day_reps']}"
def history_days(name: str, *, has_entries: bool) -> str: return f"📜 {name}\n\n{'Wybierz dzień:' if has_entries else 'Nie ma jeszcze wpisów.'}"
def history_day(name: str, performed_on: str, total_reps: str) -> str: return f"🏋️ {name}\n{performed_on}\nSuma dnia: {total_reps}"
def history_entry(name: str, performed_on: str, reps: str, total_reps: str) -> str: return f"🏋️ {name}\n\n{performed_on}\n{reps}\nRazem: {total_reps}"
def delete_confirmation(performed_on: str, reps: str) -> str: return f"Usunąć ten wpis?\n\n{performed_on}\n{reps}"
def clear_history_confirmation(name: str, entries: str, total_reps: str) -> str: return f"Wyczyścić całą historię dla {name}?\n\nWpisy: {entries}\nPowtórzenia: {total_reps}\n\nTej operacji nie można cofnąć."
def clear_history_not_needed(name: str) -> str: return f"ℹ️ {name} nie ma już wpisów do usunięcia."
def history_cleared(name: str, entries: str, total_reps: str) -> str: return f"✅ Historia {name} wyczyszczona\n\nUsunięte wpisy: {entries}\nUsunięte powtórzenia: {total_reps}"
def exercise_permanently_deleted(name: str) -> str: return f"✅ Ćwiczenie {name} zostało trwale usunięte"
def hard_delete_confirmation(name: str, entries: str, total_reps: str) -> str: return f"Usunąć {name} trwale?\n\nWpisy: {entries}\nPowtórzenia: {total_reps}\n\nĆwiczenie i cała jego historia zostaną trwale usunięte."
def result_saved(name: str, reps: str, total_reps: int, performed_on: str) -> str: return f"✅ Dodano\n\n{name}\n{reps}\n\nRazem: {total_reps}\nData: {performed_on}"
def result_input(name: str, performed_on: str) -> str: return f"🏋️ {name}\n\nData: {performed_on}\n\nWpisz wynik:\n10\n4x10\n10 9 8 7"
def result_constructor(name: str, performed_on: str, sets: str) -> str: return f"🏋️ {name}\n\nData: {performed_on}\n\nSerie:\n{sets}"
def history_constructor(name: str, sets: str) -> str: return f"✏️ {name}\n\nSerie:\n{sets}"
def settings(timezone: str, language_name: str) -> str: return f"⚙️ Ustawienia\n\nStrefa czasowa:\n{timezone}\n\nJęzyk:\n{language_name}"
CHOOSE_TIMEZONE = "🌍 Strefa czasowa\n\nWybierz strefę czasową:"
ENTER_TIMEZONE = "Wpisz strefę czasową IANA, na przykład:\n\nAsia/Tokyo\nEurope/Berlin\nAmerica/Chicago"
ENTER_TIMEZONE_REQUIRED = "Wpisz strefę czasową IANA i spróbuj ponownie."
INVALID_TIMEZONE = "Nie rozpoznano strefy czasowej. Wpisz strefę IANA i spróbuj ponownie."
TIMEZONE_CHANGED = "Strefa czasowa zmieniona"
IMPORT_SEND_FILE = "📥 <b>Import danych</b>\n\nPrześlij plik JSON z ćwiczeniami i treningami.\n\nPlik musi mieć kodowanie UTF-8 i rozmiar do 1 MB."
IMPORT_JSON_ONLY = "Obsługiwane są tylko pliki .json."
IMPORT_FILE_TOO_LARGE = "Plik jest zbyt duży. Maksymalny rozmiar to 1 MB."
IMPORT_INVALID_FILE = "Plik JSON jest nieprawidłowy lub nie pasuje do formatu importu."
IMPORT_CANCELLED = "Import anulowany"
def export_selection(*, selected: int, total: int) -> str: return f"📤 Eksport danych\n\nWybierz ćwiczenia do eksportu.\n\nWybrano: {selected} z {total}" + ("\n\nWybierz co najmniej jedno ćwiczenie." if not selected else "")
EXPORT_NO_EXERCISES = "📤 Eksport danych\n\nNie ma jeszcze ćwiczeń do eksportu."
EXPORT_FILE_TOO_LARGE = "Plik przekracza 1 MB. Wybierz mniej ćwiczeń."
def export_completed(*, exercises: str, entries: str) -> str: return f"✅ Eksport gotowy\n\nĆwiczenia: {exercises}\nWpisy treningowe: {entries}"
def import_preview(**v: object) -> str: return f"📥 Import\n\nĆwiczenia: {v['exercises']}\nWpisy treningowe: {v['entries']}\nŁącznie powtórzeń: {v['total_reps']}\nZakres dat: {v['date_from']} — {v['date_to']}\n\nNowe ćwiczenia: {v['new_count']}\nIstniejące ćwiczenia: {len(v['existing_names'])}"
def import_new_exercises_confirmation(**v: str) -> str: return f"📥 Import\n\nĆwiczenia: {v['exercises']}\nWpisy treningowe: {v['entries']}\nŁącznie powtórzeń: {v['total_reps']}\nZakres dat: {v['date_from']} — {v['date_to']}\n\nNowe ćwiczenia do utworzenia: {v['new_count']}"
def import_confirmation(strategy: str, entries: str, existing_count: int) -> str: return f"{'Zastąpić' if strategy == 'replace' else 'Scalić'} importowane dane?\n\nDodanych wpisów: {entries}."
def import_completed(**v: object) -> str: return f"✅ Import zakończony\n\nUtworzone ćwiczenia: {v['created']}\nZaktualizowane ćwiczenia: {v['updated']}\nZaimportowane wpisy: {v['entries']}\nZaimportowane powtórzenia: {v['total_reps']}"
def timezone_changed(timezone: str) -> str: return f"✅ Strefa czasowa zmieniona\n\n{timezone}"
def language_changed(language_name: str) -> str: return f"✅ Język zmieniony\n\n{language_name}"
def weekly_report_toggle(enabled: bool) -> str: return "📅 Raport tygodniowy: włączony" if enabled else "📅 Raport tygodniowy: wyłączony"
def weekly_report_changed(enabled: bool) -> str: return "Raport tygodniowy włączony" if enabled else "Raport tygodniowy wyłączony"
BUTTON_GENERATE_CARDS = "🖼 Generuj karty"
BUTTON_WEEKLY_CARD = "🖼 Karta tygodniowa"
WEEKLY_NO_DATA = "To ćwiczenie nie ma jeszcze danych z pełnych tygodni."
WEEKLY_CARD_FAILED = "Nie udało się wysłać jednej z kart. Spróbuj ponownie z menu ćwiczenia."
WEEKLY_LABELS = dict(title="📅 Raport tygodniowy", period="Okres", total="Ten tydzień: {total} {unit}", first="Brak wcześniejszego pełnego tygodnia.", previous="Poprzedni tydzień", change="Zmiana", active="Aktywne dni", best="Najlepszy dzień")
def weekly_reps_unit(total: int) -> str: return "powtórzenie" if total == 1 else "powtórzeń"
