"""Brazilian Portuguese Telegram UI copy."""
from .en import *
LANGUAGE_CODE = "pt"
LANGUAGE_NAME = "Português (Brasil)"
LANGUAGE_BUTTON = "🇧🇷 Português (Brasil)"
EXERCISES_TITLE = "🏋️ Repka\n\nEscolha um exercício"
NO_EXERCISES = "🏋️ Repka\n\nAinda não há exercícios"
BUTTON_SETTINGS = "⚙️ Configurações"
BUTTON_ADD_EXERCISE = "➕ Adicionar exercício"
BUTTON_ADD_FIRST_EXERCISE = "➕ Adicione seu primeiro exercício"
BUTTON_ADD_RESULT = "➕ Adicionar resultado"
BUTTON_STATISTICS = "📊 Estatísticas"
BUTTON_HISTORY = "📜 Histórico"
BUTTON_BACK = BUTTON_BACK_ARROW = "← Voltar"
BUTTON_CHANGE_LANGUAGE = "🌐 Idioma"
BUTTON_CHANGE_TIMEZONE = "🌍 Fuso horário"
CHOOSE_LANGUAGE = "🌐 Escolha um idioma"
LANGUAGE_CHANGED = "Idioma alterado"
TODAY, YESTERDAY, DAY_BEFORE_YESTERDAY = "Hoje", "Ontem", "Anteontem"
ENTER_RESULT = "Digite um resultado."
INVALID_RESULT_FORMAT = "Formato não reconhecido. Exemplos: 10, 4x10 ou 10 9 8."
INVALID_DATE = "Data não reconhecida. Use 25.08, 25.08.2026 ou 2026-08-25."
BACKEND_UNAVAILABLE = "O serviço está temporariamente indisponível. Tente novamente mais tarde."
BOT_NAME = "Repka · Registro de treinos"
BOT_SHORT_DESCRIPTION = "Registre exercícios, acompanhe seu progresso e receba relatórios semanais."
BOT_DESCRIPTION = "🥬 Repka é um registro de exercícios no Telegram.\n\nRegistre séries e repetições em uma linha, acompanhe seu progresso e receba relatórios semanais."
BOT_COMMANDS = {"menu": "Menu", "settings": "Configurações", "help": "Ajuda"}
WELCOME = "🥬 Olá! Eu sou a Repka.\n\nGuardo seus treinos e transformo números simples em uma visão clara do seu progresso.\n\nAdicione um exercício e envie um resultado como 16, 4×10 ou 12, 10, 8."
HELP = "ℹ️ Ajuda\n\nEscolha um exercício para adicionar um resultado, ver estatísticas ou abrir o histórico.\n\n/menu — exercícios\n/settings — configurações"
from ._translations import _apply_button_translations
_apply_button_translations(globals(), LANGUAGE_CODE)
