"""Turkish Telegram UI copy."""
from .en import *
LANGUAGE_CODE = "tr"
LANGUAGE_NAME = "Türkçe"
LANGUAGE_BUTTON = "🇹🇷 Türkçe"
EXERCISES_TITLE = "🏋️ Repka\n\nBir egzersiz seçin"
NO_EXERCISES = "🏋️ Repka\n\nHenüz egzersiz yok"
BUTTON_SETTINGS = "⚙️ Ayarlar"
BUTTON_ADD_EXERCISE = "➕ Egzersiz ekle"
BUTTON_ADD_FIRST_EXERCISE = "➕ İlk egzersizinizi ekleyin"
BUTTON_ADD_RESULT = "➕ Sonuç ekle"
BUTTON_STATISTICS = "📊 İstatistikler"
BUTTON_HISTORY = "📜 Geçmiş"
BUTTON_BACK = BUTTON_BACK_ARROW = "← Geri"
BUTTON_CHANGE_LANGUAGE = "🌐 Dil"
BUTTON_CHANGE_TIMEZONE = "🌍 Saat dilimi"
CHOOSE_LANGUAGE = "🌐 Bir dil seçin"
LANGUAGE_CHANGED = "Dil değiştirildi"
TODAY, YESTERDAY, DAY_BEFORE_YESTERDAY = "Bugün", "Dün", "Evvelsi gün"
ENTER_RESULT = "Bir sonuç girin."
INVALID_RESULT_FORMAT = "Tanınmayan biçim. Örnekler: 10, 4x10 veya 10 9 8."
INVALID_DATE = "Tanımayan tarih. 25.08, 25.08.2026 veya 2026-08-25 kullanın."
BACKEND_UNAVAILABLE = "Hizmet geçici olarak kullanılamıyor. Daha sonra tekrar deneyin."
BOT_NAME = "Repka · Antrenman Takibi"
BOT_SHORT_DESCRIPTION = "Egzersizlerinizi kaydedin, ilerlemenizi görün ve haftalık raporlar alın."
BOT_DESCRIPTION = "🥬 Repka, Telegram’da bir egzersiz takipçisidir.\n\nSetleri ve tekrarları tek satırda kaydedin, ilerlemenizi görün ve haftalık raporlar alın."
BOT_COMMANDS = {"menu": "Menü", "settings": "Ayarlar", "help": "Yardım"}
WELCOME = "🥬 Merhaba! Ben Repka.\n\nAntrenmanlarınızı kaydeder, basit sayıları ilerlemenizin açık bir hikâyesine dönüştürürüm.\n\nBir egzersiz ekleyin ve 16, 4×10 veya 12, 10, 8 gibi bir sonuç gönderin."
HELP = "ℹ️ Yardım\n\nSonuç eklemek, istatistikleri görmek veya geçmişi açmak için bir egzersiz seçin.\n\n/menu — egzersizler\n/settings — ayarlar"
from ._translations import _apply_button_translations
_apply_button_translations(globals(), LANGUAGE_CODE)
