"""Ukrainian Telegram UI copy."""
from .en import *
LANGUAGE_CODE = "uk"
LANGUAGE_NAME = "Українська"
LANGUAGE_BUTTON = "🇺🇦 Українська"
EXERCISES_TITLE = "🏋️ Repka\n\nОберіть вправу"
NO_EXERCISES = "🏋️ Repka\n\nВправ ще немає"
BUTTON_SETTINGS = "⚙️ Налаштування"
BUTTON_ADD_EXERCISE = "➕ Додати вправу"
BUTTON_ADD_FIRST_EXERCISE = "➕ Додайте першу вправу"
BUTTON_ADD_RESULT = "➕ Додати результат"
BUTTON_STATISTICS = "📊 Статистика"
BUTTON_HISTORY = "📜 Історія"
BUTTON_BACK = BUTTON_BACK_ARROW = "← Назад"
BUTTON_CHANGE_LANGUAGE = "🌐 Мова"
BUTTON_CHANGE_TIMEZONE = "🌍 Часовий пояс"
CHOOSE_LANGUAGE = "🌐 Оберіть мову"
LANGUAGE_CHANGED = "Мову змінено"
TODAY, YESTERDAY, DAY_BEFORE_YESTERDAY = "Сьогодні", "Учора", "Позавчора"
ENTER_RESULT = "Введіть результат."
INVALID_RESULT_FORMAT = "Нерозпізнаний формат. Приклади: 10, 4x10 або 10 9 8."
INVALID_DATE = "Нерозпізнана дата. Використовуйте 25.08, 25.08.2026 або 2026-08-25."
BACKEND_UNAVAILABLE = "Сервіс тимчасово недоступний. Спробуйте пізніше."
BOT_NAME = "Repka · Трекер тренувань"
BOT_SHORT_DESCRIPTION = "Записуйте вправи, відстежуйте прогрес і отримуйте тижневі звіти."
BOT_DESCRIPTION = "🥬 Repka — це трекер вправ у Telegram.\n\nЗаписуйте підходи й повторення в одному рядку, відстежуйте прогрес і отримуйте тижневі звіти."
BOT_COMMANDS = {"menu": "Меню", "settings": "Налаштування", "help": "Допомога"}
WELCOME = "🥬 Вітаю! Я Repka.\n\nЯ зберігаю ваші тренування й перетворюю прості числа на зрозумілу історію вашого прогресу.\n\nДодайте вправу та надішліть результат: 16, 4×10 або 12, 10, 8."
HELP = "ℹ️ Допомога\n\nОберіть вправу, щоб додати результат, переглянути статистику або відкрити історію.\n\n/menu — вправи\n/settings — налаштування"
from ._translations import _apply_button_translations
_apply_button_translations(globals(), LANGUAGE_CODE)
